### ISSUE TITLE
create image through docker-compose.yml 

### ISSUE THREAD

**Issue by EmanueleGuidotti** [dockage/phppgadmin#7]
I'd like to open phppgadmin in a different port. Like for example phppgadmin.websitename.test maybe using traefik.

This is my compose scritp

```
  phppgadmin:
    image: dockage/phppgadmin:latest
    container_name: "${COMPOSE_PROJECT_NAME}-phppgadmin"
    environment:
      - PHPPGADMIN_SERVER_HOST=${POSTGRES_HOST}
      - PHPPGADMIN_SERVER_PORT=5432
      - PHPPGADMIN_SERVER_DEFAULTDB=${POSTGRES_DB}
      - PHPPGADMIN_SERVER_USERNAME=${POSTGRES_USER}
      - PHPPGADMIN_SERVER_PASSWORD=${POSTGRES_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`${PPGA_SUBDOMAIN}`)"
      - "traefik.http.routers.pma.entrypoints=web,websecure"
      - "traefik.http.routers.pma.tls=true"
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - traefik-public
      - internal
```

Any help?
